export interface ProviderSpec {
  id: string;
  display_name: string;
  kind: 'cloud' | 'local' | 'aggregator' | 'custom';
  default_base_url: string | null;
  base_url_editable: boolean;
  auth: 'bearer' | 'x-api-key' | 'x-goog-api-key' | 'none';
  models_endpoint: string;
  models_parser: string;
  api_key_pattern: string | null;
  api_key_docs_url: string;
  supports_streaming: boolean;
  supports_tools: boolean;
  supports_vision: boolean;
  supported_features: string[];
}

export const PROVIDER_REGISTRY: Record<string, ProviderSpec> = {
  gemini: {
    id: 'gemini',
    display_name: 'Gemini',
    kind: 'cloud',
    default_base_url: 'https://generativelanguage.googleapis.com',
    base_url_editable: false,
    auth: 'x-goog-api-key',
    models_endpoint: '/v1beta/models',
    models_parser: 'gemini',
    api_key_pattern: '^AIza[0-9A-Za-z_-]{35}$',
    api_key_docs_url: 'https://aistudio.google.com/app/apikey',
    supports_streaming: true,
    supports_tools: true,
    supports_vision: true,
    supported_features: ['reasoning', 'system_prompt', 'json_mode'],
  },
  openai: {
    id: 'openai',
    display_name: 'OpenAI',
    kind: 'cloud',
    default_base_url: 'https://api.openai.com/v1',
    base_url_editable: false,
    auth: 'bearer',
    models_endpoint: '/models',
    models_parser: 'openai',
    api_key_pattern: '^sk-[A-Za-z0-9_-]{20,}$',
    api_key_docs_url: 'https://platform.openai.com/api-keys',
    supports_streaming: true,
    supports_tools: true,
    supports_vision: true,
    supported_features: ['reasoning', 'system_prompt', 'json_mode'],
  },
  anthropic: {
    id: 'anthropic',
    display_name: 'Anthropic',
    kind: 'cloud',
    default_base_url: 'https://api.anthropic.com/v1',
    base_url_editable: false,
    auth: 'x-api-key',
    models_endpoint: '/v1/models',
    models_parser: 'anthropic',
    api_key_pattern: '^sk-ant-[A-Za-z0-9_-]{20,}$',
    api_key_docs_url: 'https://console.anthropic.com/settings/keys',
    supports_streaming: true,
    supports_tools: true,
    supports_vision: true,
    supported_features: ['reasoning', 'system_prompt'],
  },
  groq: {
    id: 'groq',
    display_name: 'Groq',
    kind: 'cloud',
    default_base_url: 'https://api.groq.com/openai/v1',
    base_url_editable: false,
    auth: 'bearer',
    models_endpoint: '/models',
    models_parser: 'openai',
    api_key_pattern: '^gsk_[A-Za-z0-9]{20,}$',
    api_key_docs_url: 'https://console.groq.com/keys',
    supports_streaming: true,
    supports_tools: true,
    supports_vision: false,
    supported_features: ['reasoning', 'system_prompt', 'json_mode'],
  },
  openrouter: {
    id: 'openrouter',
    display_name: 'OpenRouter',
    kind: 'aggregator',
    default_base_url: 'https://openrouter.ai/api/v1',
    base_url_editable: false,
    auth: 'bearer',
    models_endpoint: '/models',
    models_parser: 'openai',
    api_key_pattern: '^sk-or-v1-[A-Za-z0-9]+$',
    api_key_docs_url: 'https://openrouter.ai/keys',
    supports_streaming: true,
    supports_tools: true,
    supports_vision: true,
    supported_features: ['reasoning', 'system_prompt', 'json_mode'],
  },
  nvidia_nim: {
    id: 'nvidia_nim',
    display_name: 'NVIDIA NIM',
    kind: 'cloud',
    default_base_url: 'https://integrate.api.nvidia.com/v1',
    base_url_editable: true,
    auth: 'bearer',
    models_endpoint: '/models',
    models_parser: 'openai',
    api_key_pattern: '^nvapi-[A-Za-z0-9_-]{20,}$',
    api_key_docs_url: 'https://build.nvidia.com/settings/api-keys',
    supports_streaming: true,
    supports_tools: true,
    supports_vision: true,
    supported_features: ['reasoning', 'system_prompt', 'json_mode'],
  },
  ollama: {
    id: 'ollama',
    display_name: 'Ollama',
    kind: 'local',
    default_base_url: 'http://localhost:11434',
    base_url_editable: true,
    auth: 'none',
    models_endpoint: '/api/tags',
    models_parser: 'ollama_tags',
    api_key_pattern: null,
    api_key_docs_url: 'https://ollama.com',
    supports_streaming: true,
    supports_tools: true,
    supports_vision: true,
    supported_features: ['reasoning', 'system_prompt', 'json_mode'],
  },
  lm_studio: {
    id: 'lm_studio',
    display_name: 'LM Studio',
    kind: 'local',
    default_base_url: 'http://localhost:1234/v1',
    base_url_editable: true,
    auth: 'none',
    models_endpoint: '/models',
    models_parser: 'openai',
    api_key_pattern: null,
    api_key_docs_url: 'https://lmstudio.ai',
    supports_streaming: true,
    supports_tools: true,
    supports_vision: true,
    supported_features: ['reasoning', 'system_prompt', 'json_mode'],
  },
  openai_compatible: {
    id: 'openai_compatible',
    display_name: 'OpenAI-Compatible',
    kind: 'custom',
    default_base_url: null,
    base_url_editable: true,
    auth: 'bearer',
    models_endpoint: '/models',
    models_parser: 'openai',
    api_key_pattern: null,
    api_key_docs_url: '',
    supports_streaming: true,
    supports_tools: true,
    supports_vision: true,
    supported_features: ['reasoning', 'system_prompt', 'json_mode'],
  },
};
